Physics
ankomas/2019_1C_K3051_BackBuffer pull request #13
Opened 2019-05-02 17:22 UTC by JuanAmarillo

2019-05-02 18:08 UTC, ankomas requested changes
En general esta bien, lo unico que hay que cambiar es lo del vector de la gravedad,y estaria bueno que la masa y que tipo de rigid body se tiene que utilizar este en alguna abstraccion como
abstraccion{
mesh pez,
body x,
}
capaz en vez de el MeshRepository tener un repository de esa abstraccion

Edit: estaria bueno tambien que en base a eso ya se tengan factories instanciados asi no hay que hacerlos cada vez que se crea un chunk

2019-05-02 18:08 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactory.cs
> +            newMesh.updateBoundingBox();
creo que cuando seteas Scale ya hace por adentro un updateBoundingBox, creo

2019-05-02 18:08 UTC, ankomas commented on TGC.Group/Model/Elements/RigidBodyFactories/BoxFactory.cs
> +            var halfSize = new TGCVector3(plane.Size.X, 0, plane.Size.Z).ToBulletVector3();
halfSize?

2019-05-02 18:08 UTC, ankomas commented on TGC.Group/Model/Elements/RigidBodyFactories/BoxFactory.cs
> +            PhysicsWorld.DynamicsWorld.AddRigidBody(rigidBody);
medio raro que aca se agregue el elemento al mundo

2019-05-02 18:08 UTC, ankomas commented on TGC.Group/Model/Elements/RigidBodyFactories/CapsuleFactory.cs
> +                Gravity = new TGCVector3(0, -10, 0).ToBulletVector3()
Crear el vector gravedad por cada instancia no esta bueno, es mejor tenerlo en un static final y pasarle la referencia

2019-05-02 18:08 UTC, ankomas commented on TGC.Group/Model/PhysicsWorld.cs
> +                Gravity = new TGCVector3(0, -10f, 0).ToBulletVector3()
Lo mismo de la gravedad

2019-05-02 18:10 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/ElementFactory.cs
> +            newMesh.updateBoundingBox();
no lo hace, al primer update lo hacias antes

2019-05-02 18:15 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactory.cs
> +            newMesh.updateBoundingBox();
https://github.com/tgc-utn/tgc-viewer/blob/3584a6e6def91b8fddfaf5aa7fd61ffefa9d0ed3/TGC.Core/SceneLoader/TgcMesh.cs#L477

2019-05-02 18:59 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/ElementFactory.cs
> +            newMesh.updateBoundingBox();
me confundí, lo que necesitaba era el UpdateMeshTransform

2019-05-02 19:00 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/RigidBodyFactories/BoxFactory.cs
> +            var halfSize = new TGCVector3(plane.Size.X, 0, plane.Size.Z).ToBulletVector3();
mal, quedo de una abstracción anterior que termine cambiando a las apuradas

2019-05-02 19:01 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/RigidBodyFactories/BoxFactory.cs
> +            PhysicsWorld.DynamicsWorld.AddRigidBody(rigidBody);
sip, lo iba a cambiar para soportar varios mundos, tipo en agua se coporta diferente que en superficie

2019-05-02 19:02 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/RigidBodyFactories/CapsuleFactory.cs
> +                Gravity = new TGCVector3(0, -10, 0).ToBulletVector3()
es verdad, estaba mas que nada por debug, no debería ni estar ahí, debe estar en la fisica del mundo

2019-05-02 19:02 UTC, JuanAmarillo commented on TGC.Group/Model/PhysicsWorld.cs
> +                Gravity = new TGCVector3(0, -10f, 0).ToBulletVector3()
idem anterior

2019-05-04 23:01 UTC, ankomas approved these changes

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/AquaticPhysics.cs
> +            {
Podria ser directamente una clase estatica

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Chunks/Chunk.cs
> +            this.Physics = physicsWorld;
PhysicsWorld taria mejor de nombre de atirbuto

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Chunks/FloorChunk.cs
> +            CreateFloor(origin);
CreateElements no agrega los elementos al mundo fisico pero CreateFloor si, estaria bueno que los dos o agreguen o no agreguen

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactories/CoralFactory.cs
> +                if (instance == null)
Lo mismo, podria ser una clase estatica

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactories/ElementFactory.cs
> +            return new Element(mesh, rigidBody);
Create Generate como que es lo mismo, podrias hacer el return new element en el create

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactories/ElementFactory.cs
> +            newMesh.updateBoundingBox();
El updateBoundingBox ya se hace cuando cambias la escala

2019-05-04 23:01 UTC, ankomas commented on TGC.Group/Model/Elements/ElementFactories/FishFactory.cs
> +            get
Clase estatica

2019-05-04 23:04 UTC, JuanAmarillo commented on TGC.Group/Model/AquaticPhysics.cs
> +            {
quiero que herede en algún momento e implementar un par de cosillas jaja

2019-05-04 23:05 UTC, JuanAmarillo commented on TGC.Group/Model/Chunks/Chunk.cs
> +            this.Physics = physicsWorld;
el IDE es chilla cuando le pongo el mismo nombre que la clase xd

2019-05-04 23:11 UTC, JuanAmarillo commented on TGC.Group/Model/Elements/ElementFactories/ElementFactory.cs
> +            return new Element(mesh, rigidBody);
I know, pero bueno un trick para overridear el metodo en los otros factories xd

2019-05-04 23:31 UTC, merged